DROP TABLE IF EXISTS TBL_USER_DETAILS;
  
CREATE TABLE TBL_USER_DETAILS (
  user_id VARCHAR(50) PRIMARY KEY,
  password VARCHAR(500) NOT NULL
);

    
INSERT INTO TBL_USER_DETAILS (user_id,password) VALUES
  ('Admin','$2a$12$a6caCGfGeaDajbZ1Rp1LP.0S5HoZp3js9j9aMPrpn/tY3AppKBcp.'),
  ('User','$2a$12$a6caCGfGeaDajbZ1Rp1LP.0S5HoZp3js9j9aMPrpn/tY3AppKBcp.');
  
  DROP TABLE IF EXISTS TBL_JWT;
  CREATE TABLE TBL_JWT (
  token VARCHAR(500));